-- Session reports v4.0.4 columns for qualia-framework
-- Framework v4.0.4 sends two new fields:
--   client_report_id — per-project sequential ID (QS-REPORT-NN), stable across retries.
--     Preferred UPSERT dedupe key together with framework_project_id.
--   dry_run — synthetic ping from `qualia-framework erp-ping`.
--     Must be filterable out of production views and expire after 7 days.

BEGIN;

-- ────────────────────────────────────────────────────────────
-- New columns
-- ────────────────────────────────────────────────────────────

ALTER TABLE session_reports ADD COLUMN IF NOT EXISTS client_report_id text;
ALTER TABLE session_reports ADD COLUMN IF NOT EXISTS dry_run boolean NOT NULL DEFAULT false;

-- ────────────────────────────────────────────────────────────
-- Indexes
-- ────────────────────────────────────────────────────────────

-- Idempotent UPSERT key for v4.0.4 payloads.
-- Both identifiers must be present; legacy v3.x payloads (NULL framework_project_id
-- or NULL client_report_id) fall through and insert normally.
CREATE UNIQUE INDEX IF NOT EXISTS session_reports_client_report_id_uniq
  ON session_reports(framework_project_id, client_report_id)
  WHERE client_report_id IS NOT NULL AND framework_project_id IS NOT NULL;

-- Production-reads hot path: list real reports per project, newest first.
-- Excludes dry_run rows so dashboard queries never see synthetic pings.
CREATE INDEX IF NOT EXISTS session_reports_active_idx
  ON session_reports(project_name, submitted_at DESC)
  WHERE dry_run = false;

-- Cleanup helper: the 7-day TTL cron deletes expired dry_run rows.
-- This partial index keeps that DELETE cheap.
CREATE INDEX IF NOT EXISTS session_reports_dry_run_expiry_idx
  ON session_reports(submitted_at)
  WHERE dry_run = true;

-- ────────────────────────────────────────────────────────────
-- Column documentation
-- ────────────────────────────────────────────────────────────

COMMENT ON COLUMN session_reports.client_report_id IS 'Per-project sequential report ID generated by qualia-framework v4.0.4+ (format QS-REPORT-NN). Stable across retries. Together with framework_project_id forms the preferred UPSERT dedupe key.';
COMMENT ON COLUMN session_reports.dry_run IS 'True for synthetic pings sent by `qualia-framework erp-ping`. These rows are excluded from production views and expire after 7 days via cron cleanup.';

COMMIT;

-- ────────────────────────────────────────────────────────────
-- DOWN (manual rollback reference — do not execute automatically)
-- ────────────────────────────────────────────────────────────
-- DROP INDEX IF EXISTS session_reports_dry_run_expiry_idx;
-- DROP INDEX IF EXISTS session_reports_active_idx;
-- DROP INDEX IF EXISTS session_reports_client_report_id_uniq;
-- ALTER TABLE session_reports DROP COLUMN IF EXISTS dry_run;
-- ALTER TABLE session_reports DROP COLUMN IF EXISTS client_report_id;
